name: cwr
version: 0.1
summary: Cloud Weather Report (cwr) 
description: more here
confinement: devmode  # use "strict" to enforce system access only via declared interfaces

apps:
    cwr:
        command: cwr

parts:
    cwr:
        source: https://github.com/juju-solutions/cloud-weather-report.git
        plugin: python2
        stage-packages:
            - unzip
            - make
        python-packages: [PyYAML==3.11]
